import { TokenType } from './lexer/token';

export const KEYBOARD_LAYOUT: Record<string, [number, number]> = {
    q: [0, 0],
    w: [1, 0],
    e: [2, 0],
    r: [3, 0],
    t: [4, 0],
    y: [5, 0],
    u: [6, 0],
    i: [7, 0],
    o: [8, 0],
    p: [9, 0],
    a: [0.5, 1],
    s: [1.5, 1],
    d: [2.5, 1],
    f: [3.5, 1],
    g: [4.5, 1],
    h: [5.5, 1],
    j: [6.5, 1],
    k: [7.5, 1],
    l: [8.5, 1],
    z: [1.5, 2],
    x: [2.5, 2],
    c: [3.5, 2],
    v: [4.5, 2],
    b: [5.5, 2],
    n: [6.5, 2],
    m: [7.5, 2],
};

export const KEYWORDS: Record<string, TokenType> = {
    orbit: TokenType.KeywordOrbit,
    let: TokenType.KeywordLet,
    var: TokenType.KeywordVar,
    fn: TokenType.KeywordFn,
    if: TokenType.KeywordIf,
    else: TokenType.KeywordElse,
    for: TokenType.KeywordFor,
    while: TokenType.KeywordWhile,
    loop: TokenType.KeywordLoop,
    in: TokenType.KeywordIn,
    return: TokenType.KeywordReturn,
    break: TokenType.KeywordBreak,
    match: TokenType.KeywordMatch,
    true: TokenType.KeywordTrue,
    false: TokenType.KeywordFalse,
    struct: TokenType.KeywordStruct,
    int: TokenType.KeywordInt,
    float: TokenType.KeywordFloat,
    str: TokenType.KeywordStr,
    bool: TokenType.KeywordBool,
};
